language: objective-c
osx_image: xcode9
script: xcodebuild test -project MQTTClient/MQTTClient.xcodeproj -scheme MQTTClientiOSTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.1'
