language: objective-c
osx_image: xcode10
env:
  matrix:
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=11.4'
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=12.0'
    - SCHEME=MQTTClientmacOS DESTINATION='platform=macOS'
before_install:
  - gem install xcpretty
  - brew install mosquitto
install:
    xcodebuild -destination generic/platform=iOS -workspace Example/Example.xcworkspace -scheme "Example"
before_script: ./brokers/mosquitto/start.sh
script: xcodebuild clean test -workspace MQTTClient/MQTTClient.xcworkspace -scheme $SCHEME -destination "$DESTINATION"
after_script: ./brokers/mosquitto/stop.sh
after_success:
  - if [ "$SCHEME" == "MQTTClientmacOS" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
    
addons:
  browserstack:
    username: "markrobinson21"
    access_key:
      secure: "nFBGconUssll+PN4C7ENawVmCV7wLMkLNL2r6EZnwdQkLLEd1IeftuomS2meXbTANPJdki0FRfo85Q1icxUb/L4Juz8LFf6v4mJ55m//E84WyDhlzKdOYftTDNuDrMT88qNwBREa1clPnX38Xztq1KiEiTwoqZkaIwJRn0hrmHCnlLguixaaymfL0mhpOr4CWsIcTWwuBK0X6kb1KDaZqzd3kvcDxza+XAPQbbr//r3qRb4NqSpcyh5LXQzIbyAGKKajNIDAwjLxJV5N0Z0IlswNFGt5sLjAfHgouH8dcLhEldbnGbocvlDVK8L6k9GUGNHxNPnw17Wa9CI4pbXkcUcex9/P2maSMf8nMwj8WxIrR07nLh218sRI7ts878I5T/qi432zvgqfliI5hlowomWgMTRV6QcJKhU+KP30EykwCoyqVTie4dQuvnxogQRG6AKNt0DhZ5m7UYLvzYTgirYy0GZDC4OZZpg1drc6RsIM1PmmGCvTHVU7WN+CXHxxhJ7qNVqG4r9nrUzeqNeHuVQNZWnjZnG2vkBmyCpsh6H4LrGyVv7Fpi88ABn+735GqgnQAt0kW+ECBqofXCCZb9oVBQf/PMoi4T01fo6fnqzya3+hhqiPFtgnq2ewENz9QlRne/8FtH/cWSOB1O1nFnPHCIVDocdrxpC1Bla3IKA="
