language: objective-c
osx_image: xcode9
env:
  matrix:
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 6 Plus,OS=11.0'
    - SCHEME=MQTTClientmacOS DESTINATION='platform=macOS'
before_install:
  - gem install xcpretty
  - brew install mosquitto
before_script: ./brokers/mosquitto/start.sh
script: xcodebuild clean test -project MQTTClient/MQTTClient.xcodeproj -scheme $SCHEME -destination $DESTINATION | xcpretty && exit ${PIPESTATUS[0]}
after_script: ./brokers/mosquitto/stop.sh
