language: objective-c
osx_image: xcode9
before_install:
  - gem install xcpretty
script: xcodebuild clean test -project MQTTClient/MQTTClient.xcodeproj -scheme MQTTClientiOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=11.0' | xcpretty && exit ${PIPESTATUS[0]}
